FROM ethereum/solc:0.8.28 AS solidity
FROM ethereum/solc:0.5.16 AS solidity_5_16
FROM ubuntu:20.04 AS contracts
RUN apt-get update && \
    DEBIAN_FRONTEND=nontineractive apt-get -y install xxd && \
    rm -rf /var/lib/apt/lists/* /var/lib/apt/cache/*
COPY solidity/ /opt/

# solc 0.8.0
COPY --from=solidity /usr/bin/solc /usr/bin/solc
WORKDIR /opt/
RUN solc --optimize --optimize-runs 200 --output-dir . --bin --abi *.sol && \
    for file in $(ls *.bin); do xxd -r -p $file >${file}ary; done && \
        ls -l

# solc 0.5.16
COPY --from=solidity_5_16 /usr/bin/solc /usr/bin/solc
WORKDIR /opt/uniswap
RUN solc --optimize --optimize-runs 200 --output-dir . --bin --abi *.sol && \
    for file in $(ls *.bin); do xxd -r -p $file >${file}ary; done && \
        ls -l
