services:
  solana:
    container_name: solana
    image: romelabs/rome-evm:${ROME_EVM_TAG:-latest}
    environment:
      RUST_LOG: solana_runtime::system_instruction_processor=debug,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  reg_rollup:
    container_name: reg_rollup
    image: romelabs/rome-apps:${CLI_TAG:-latest}
    environment:
      SERVICE_NAME: cli.sh
      CHAIN_ID: 1001
      PROGRAM_KEYPAIR: /opt/rome-keypair.json
      SOLANA_RPC: http://solana:8899
      COMMAND: reg-rollup
      ROLLUP_OWNER: /opt/rollup-owner-keypair.json
      UPGRADE_AUTHORITY: /opt/upgrade-authority-keypair.json
    volumes:
      - ./keys/rome-keypair.json:/opt/rome-keypair.json
      - ./keys/rollup-owner-keypair.json:/opt/rollup-owner-keypair.json
      - ./keys/upgrade-authority-keypair.json:/opt/upgrade-authority-keypair.json
    depends_on:
      solana:
        condition: service_healthy
    networks:
      - net

  create_balance:
    container_name: create_balance
    image: romelabs/rome-apps:${CLI_TAG:-latest}
    environment:
      SERVICE_NAME: cli.sh
      CHAIN_ID: 1001
      PROGRAM_KEYPAIR: /opt/rome-keypair.json
      SOLANA_RPC: http://solana:8899
      COMMAND: create-balance
      ADDRESS: 0x768b73EE6CA9e0A1bc32868CA65dB89E44696DD8
      BALANCE: '1000000000000000000000'
      KEYPAIR: /opt/rollup-owner-keypair.json
    volumes:
      - ./keys/rome-keypair.json:/opt/rome-keypair.json
      - ./keys/rollup-owner-keypair.json:/opt/rollup-owner-keypair.json
    depends_on:
      solana:
        condition: service_healthy
    networks:
      - net

  geth:
    container_name: geth
    image: romelabs/rollup-op-geth:${GETH_TAG:-latest}
    hostname: geth
    environment:
      CHAIN_ID: '1001'
      GENESIS_ADDRESS: 0x768b73EE6CA9e0A1bc32868CA65dB89E44696DD8
      GENESIS_BALANCE: '1000000000000000000000'
      GENESIS_PRIVATE_KEY: 3f37802575d0840281551d5619256a84762e8236325537e8818730082645be65
      GETH_HOST: localhost:3000
      JWT_SECRET: a535c9f4f9df8e00cd6a15a7baa74bb92ca47ebdf59b6f3f2d8a8324b6c1767c
      ROME_GASOMETER_URL: http://proxy:9090
    ports:
      - 443:443
      - 8080:80
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 3000:3000
    networks:
      - net
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: [
        CMD-SHELL,
        "curl --location 'localhost:8545' --header 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83}'"
      ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  geth2:
    container_name: geth2
    image: romelabs/rollup-op-geth:${GETH_TAG:-latest}
    hostname: geth1
    environment:
      CHAIN_ID: '1002'
      GENESIS_ADDRESS: 0x768b73EE6CA9e0A1bc32868CA65dB89E44696DD8
      GENESIS_BALANCE: '1000000000000000000000'
      GETH_HOST: localhost:3000
      JWT_SECRET: a535c9f4f9df8e00cd6a15a7baa74bb92ca47ebdf59b6f3f2d8a8324b6c1767c
      ROME_GASOMETER_URL: http://proxy2:9090
    ports:
      - 444:443
      - 8081:80
      - 8547:8545
      - 8548:8546
      - 8552:8551
    networks:
      - net
    depends_on:
      proxy2:
        condition: service_healthy
    healthcheck:
      test: [
        CMD-SHELL,
        "curl --location 'localhost:8545' --header 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83}'"
      ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  rhea:
    container_name: rhea
    image: romelabs/rome-apps:${RHEA_TAG:-latest}
    hostname: rhea
    environment:
      SERVICE_NAME: rhea
      RHEA_CONFIG: /opt/rhea-config.yml
    volumes:
      - ./cfg/rhea-config.yml:/opt/rhea-config.yml
      - ./keys/rome-keypair.json:/opt/rome-keypair.json
      - ./keys/rhea-sender.json:/opt/rhea-sender.json
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
      geth:
        condition: service_healthy
        
  proxy:
    container_name: proxy
    image: romelabs/rome-apps:${PROXY_TAG:-latest}
    hostname: proxy
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/proxy-config.yml
    volumes:
      - ./cfg/proxy-config1.yml:/opt/proxy-config.yml
      - ./keys/rome-keypair.json:/opt/rome-keypair.json
      - ./keys/proxy-sender.json:/opt/proxy-sender.json
    ports:
      - 9090:9090
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    healthcheck:
      test: [
        CMD-SHELL,
        "curl --location 'proxy:9090' --header 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83}'"
      ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  proxy2:
    container_name: proxy2
    image: romelabs/rome-apps:${PROXY_TAG:-latest}
    hostname: proxy2
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/proxy-config.yml
    volumes:
      - ./cfg/proxy-config2.yml:/opt/proxy-config.yml
      - ./keys/rome-keypair.json:/opt/rome-keypair.json
      - ./keys/proxy-sender.json:/opt/proxy-sender.json
    ports:
      - 9092:9090
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    healthcheck:
      test: [
        CMD-SHELL,
        "curl --location 'proxy2:9090' --header 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":83}'"
      ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
networks:
  net: