chain_id: 1001
program_id: "CmobH2vR6aUtQ8x4xd1LYNiH6k2G7PFT5StTgWqvy2VU"
start_slot: 0
solana:
  rpc_url: "http://solana:8899"
  commitment: "confirmed"
payers:
  - payer_keypair: "/opt/ci/keys/test-account-keypair.json"
    fee_recipients:
      - 0xe235b9caf55b58863Ae955A372e49362b0f93726
      - 0x8870D7800Dd9B1CF34DBC54D348F70A342A4606D
upgrade_authority_keypair: "/opt/ci/keys/upgrade-authority-keypair.json"
user_keypair: "/opt/ci/keys/test-account-keypair.json"
number_holders: 256
proxy_host: "0.0.0.0:9090"
