program_id: "CmobH2vR6aUtQ8x4xd1LYNiH6k2G7PFT5StTgWqvy2VU"
chain_id: 1001
start_slot: 0
solana:
  rpc_url: "http://solana:8899"
  commitment: "confirmed"
payers:
  - payer_keypair: "/opt/keys/proxy-sender.json"
    number_holders: 32
ethereum_storage:
  type: "pg_storage"
  connection:
    database_url: "postgres://hercules:qwerty123@postgres/test_rollup"
    max_connections: 16
proxy_host: "0.0.0.0:9090"
max_slot_history: 4096
gas_price: 1000000000
