name: ci_pipeline

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

env:
  REF_NAME: ${{github.ref_name}}
  ROME_SDK_REF_NAME: v0.1.0
  ROME_EVM_REF_NAME: v0.1.0

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout rome-evm-private reposotory'
        uses: actions/checkout@master
        with:
          path: rome-evm-private
          repository: rome-protocol/rome-evm-private
          ref: ${{env.ROME_EVM_REF_NAME}}
          token: ${{secrets.GIT_ROLLUP_TOKEN}}
      
      - name: 'Checkout rome-sdk reposotory'
        uses: actions/checkout@master
        with:
          repository: rome-protocol/rome-sdk
          path: rome-sdk
          submodules: recursive
          ref: ${{env.ROME_SDK_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout tests repository'
        uses: actions/checkout@v4
        with:
          path: tests
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build tests image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: tests/ci/Dockerfile
          tags: romeprotocol/tests:${{env.REF_NAME}}
          labels: romeprotocol/tests:${{env.REF_NAME}}


      - name: 'Set latest tag'
        if: |
          ( github.ref_name == 'master' )
        run: |
          
          docker pull romeprotocol/tests:${REF_NAME}
          docker tag romeprotocol/tests:${REF_NAME} romeprotocol/tests:latest
          docker push romeprotocol/tests:latest
      
