name: build_docker_image

on:
  workflow_call:
    inputs:
      rome_evm_ref_name:
        type: string
        description: 'rome-evm branch name to use for building the image'
        required: false
        default: 'main'
      rome_sdk_ref_name:
        type: string
        description: 'rome-sdk branch name to use for building the image'
        required: false
        default: 'main'
      rome_tests_ref_name:
        type: string
        description: 'Test repo branch name to use for building the tests'
        required: false
        default: 'main'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Prepare environment variables from input'
        id: prepare_env
        run: |
          rome_evm_ref_name='${{ inputs.rome_evm_ref_name || 'main' }}'
          rome_sdk_ref_name='${{ inputs.rome_sdk_ref_name || 'main' }}'
          rome_tests_ref_name='${{ inputs.rome_tests_ref_name || 'main' }}'
          echo "ROME_EVM_REF_NAME=$rome_evm_ref_name" >> $GITHUB_ENV
          echo "ROME_SDK_REF_NAME=$rome_sdk_ref_name" >> $GITHUB_ENV
          echo "ROME_TESTS_REF_NAME=$rome_tests_ref_name" >> $GITHUB_ENV

      - name: 'Checkout rome-evm reposotory'
        uses: actions/checkout@master
        with:
          path: rome-evm
          repository: rome-labs/rome-evm
          ref: ${{env.ROME_EVM_REF_NAME}}
          token: ${{secrets.GIT_ROLLUP_TOKEN}}
      
      - name: 'Checkout rome-sdk reposotory'
        uses: actions/checkout@master
        with:
          repository: rome-labs/rome-sdk
          path: rome-sdk
          submodules: recursive
          ref: ${{env.ROME_SDK_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout tests repository'
        uses: actions/checkout@v4
        with:
          repository: rome-labs/tests
          path: tests
          ref: ${{env.ROME_TESTS_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}
  
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build tests image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: tests/ci/Dockerfile
          tags: romelabs/tests:${{env.ROME_TESTS_REF_NAME}}
          labels: romelabs/tests:${{env.ROME_TESTS_REF_NAME}}

